git-debimport patch_2.7.1-6.debian.tar.xz

diff --git a/tests/crlf-handling b/tests/crlf-handling
--- a/tests/crlf-handling
+++ b/tests/crlf-handling
@@ -1,4 +1,4 @@
-# Copyright (C) 2009 Free Software Foundation, Inc.
+# Copyright (C) 2009, 2011-2012 Free Software Foundation, Inc.
 #
 # Copying and distribution of this file, with or without modification,
 # in any medium, are permitted without royalty provided the copyright
@@ -8,7 +8,8 @@
 
 . $srcdir/test-lib.sh
 
-require_diff
+require_gnu_diff
+require_sed
 use_local_patch
 use_tmpdir
 
@@ -22,21 +23,21 @@ echo 1b > b
 diff a b | lf2crlf > ab.diff
 echo 1 > c
 check 'patch c < ab.diff' <<EOF
-(Stripping trailing CRs from patch.)
+(Stripping trailing CRs from patch; use --binary to disable.)
 patching file c
 EOF
 
 diff -c a b | lf2crlf > ab.diff
 echo 1 > c
 check 'patch c < ab.diff' <<EOF
-(Stripping trailing CRs from patch.)
+(Stripping trailing CRs from patch; use --binary to disable.)
 patching file c
 EOF
 
 diff -u a b | lf2crlf > ab.diff
 echo 1 > c
 check 'patch c < ab.diff' <<EOF
-(Stripping trailing CRs from patch.)
+(Stripping trailing CRs from patch; use --binary to disable.)
 patching file c
 EOF
 
@@ -59,7 +60,7 @@ check 'patch c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
@@ -71,7 +72,7 @@ check 'patch c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
@@ -83,18 +84,21 @@ check 'patch c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
 # --------------------------------------------------------------
 
-diff -e a b > ab.diff
-cp a c
-check 'patch c < ab.diff' <<EOF
-EOF
+if ! have_ed ; then
+    echo "The ed utility is not available; skipping ed related tests"
+else
+    diff -e a b > ab.diff
+    cp a c
+    ncheck 'patch c < ab.diff'
+fi
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
@@ -105,12 +109,20 @@ echo 1b > b
 
 diff a b | lf2crlf > ab.diff
 cp a c
+
+check 'patch --binary c < ab.diff || echo status: $?' <<EOF
+patching file c
+Hunk #1 FAILED at 1 (different line endings).
+1 out of 1 hunk FAILED -- saving rejects to file c.rej
+status: 1
+EOF
+
 check 'patch c < ab.diff' <<EOF
-(Stripping trailing CRs from patch.)
+(Stripping trailing CRs from patch; use --binary to disable.)
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b$
 EOF
 
@@ -119,7 +131,7 @@ check 'patch --binary c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
@@ -128,11 +140,11 @@ EOF
 diff -u a b | lf2crlf > ab.diff
 cp a c
 check 'patch c < ab.diff' <<EOF
-(Stripping trailing CRs from patch.)
+(Stripping trailing CRs from patch; use --binary to disable.)
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b$
 EOF
 
@@ -141,7 +153,7 @@ check 'patch --binary c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
@@ -150,11 +162,11 @@ EOF
 diff -c a b | lf2crlf > ab.diff
 cp a c
 check 'patch c < ab.diff' <<EOF
-(Stripping trailing CRs from patch.)
+(Stripping trailing CRs from patch; use --binary to disable.)
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b$
 EOF
 
@@ -163,7 +175,7 @@ check 'patch --binary c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 1b^M$
 EOF
 
@@ -175,6 +187,10 @@ EOF
 
 # ==============================================================
 
+# Line endings of @@ lines are not used for guessing if a patch needs CR
+# stripping: if the -p / --show-c-function option of GNU diff is used, these
+# lines can have different line endings than the rest of the patch.
+
 echo 1 > a
 echo 2 > b
 diff -u a b | sed -e 's,@@$,@@ context\r,' > ab.diff
@@ -184,6 +200,6 @@ check 'patch c < ab.diff' <<EOF
 patching file c
 EOF
 
-check 'cat -A c' <<EOF
+check 'cat -ve c' <<EOF
 2$
 EOF
